---
- name: Check if we have efm.properties file or not
  stat:
    path: "{{ efm_properties }}"
  become: yes
  register: stat_efm_properties

- name: Check if we have efm.nodes file or not
  stat:
    path: "{{ efm_properties }}"
  become: yes
  register: stat_efm_nodes

- name: Create efm properties file
  copy:
    src: "{{ efm_properties }}.in"
    dest: "{{ efm_properties }}"
    owner: "{{ pg_efm_user }}"
    group: "{{ pg_efm_user }}"
    remote_src: yes
  when: not stat_efm_properties.stat.exists
  become: yes

- name: Create efm nodes file
  copy:
    src: "{{ efm_node_file }}.in"
    dest: "{{ efm_node_file }}"
    owner: "{{ pg_efm_user }}"
    group: "{{ pg_efm_user }}"
    remote_src: yes
  when: not stat_efm_nodes.stat.exists
  become: yes
