---
- name: Check if we have efm.properties file or not
  stat:
    path: "{{ efm_properties }}"
  become: yes
  register: stat_efm_properties

- name: Create efm properties file
  copy:
    src: "{{ efm_properties }}.in"
    dest: "{{ efm_properties }}"
    owner: "{{ pg_efm_user }}"
    group: "{{ pg_efm_user }}"
    remote_src: yes
  when: not stat_efm_properties.stat.exists
  become: yes

- name: Copy the efm.nodes.template to the server
  template:
    src: efm.nodes.template
    dest: "{{ efm_node_file }}"
    owner: "{{ pg_efm_user }}"
    group: "{{ pg_efm_user }}"
    mode: 0644
  become: yes
  register: efm_nodes_update
