---

- name: Start the PG Service
  systemd:
      name: "{{ PG_SERVICE }}"
      daemon_reload: yes
      state: started
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Stop the PG Service
  systemd:
      name: "{{ PG_SERVICE }}"
      daemon_reload: yes
      state: stopped
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Restart the PG Service
  systemd:
      name: "{{ PG_SERVICE }}"
      daemon_reload: yes
      state: restarted
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Reload the PG Service
  systemd:
      name: "{{ PG_SERVICE }}"
      daemon_reload: yes
      state: reloaded
  delegate_to: "{{ item.value.public_ip }}"
  become: yes
