---
- name: Generate PgBouncer auth. file {{ pgbouncer_auth_file }}
  template:
    backup: yes
    dest: "{{ pgbouncer_auth_file }}"
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0600
    src: userlist.txt.template
  delegate_to: "{{ item.value.public_ip }}"

- name: Reload PgBouncer configuration
  shell:
    cmd: kill -HUP $(cat {{ pgbouncer_pid_file }})
  delegate_to: "{{ item.value.public_ip }}"
