---
# default empty rpm repo
# port constants

os: ""
pg_version: "12"

force_replication: false
use_hostname: false

synchronous_standby_names: ""
synchronous_standbys: []
standby_quorum_type: "any"

pass_dir: "~/.edb"

primary_private_ip: ""
primary_public_ip: ""
primary_host_name: ""
standby_names: []
pg_allow_ip_addresses: []
standby_physical_slots: []
etc_hosts_lists: []

supported_os:
  - CentOS7
  - CentOS8
  - RHEL7
  - RHEL8

supported_pg_type:
  - EPAS
  - PG

supported_pg_version:
  - 10
  - 11
  - 12
  - 13

supported_node_type:
  - primary
  - standby
