---
servers:
  primary:
    node_type:  primary
    public_ip: xx.xx.xx.xx
    private_ip: xx.xx.xx.xx
  standby1:
    node_type: standby
    public_ip: xx.xx.xx.xx
    private_ip: xx.xx.xx.xx
    replication_type: synchronous
  standby2:
    node_type: standby
    public_ip: xx.xx.xx.xx
    private_ip: xx.xx.xx.xx
    replication_type: asynchronous
