---
servers:
  pemserver:
    node_type: pemserver
    public_ip: xx.xx.xx.xx
    private_ip: xx.xx.xx.xx
  primary:
    node_type:  primary
    pem_agent: true
    public_ip: xx.xx.xx.xx
    private_ip: xx.xx.xx.xx
  standby1:
    node_type: standby
    pem_agent: true
    replication_type: synchronous
    public_ip: xx.xx.xx.xx
    private_ip: xx.xx.xx.xx
  standby2:
    node_type: standby
    pem_agent: true
    replication_type: asynchronous
    public_ip: xx.xx.xx.xx
    private_ip: xx.xx.xx.xx
