---
- hosts: localhost
  name: Configure Postgres SQL Replication on Instances
  #connection: local
  become: true
  gather_facts: no

  # When using collections
  #collections:
  #    - edb_devops.edb_postgres

  vars_files:
    - hosts.yml

  pre_tasks:
      - name: Initialize the user defined variables
        set_fact:
            OS: "CentOS7"
            PG_VERSION: "12"
            PG_TYPE: "PG"
            PG_DATA: "/data/pgdata"
            PG_WAL: "/data/pg_wal"
            EDB_YUM_USERNAME: ""
            EDB_YUM_PASSWORD: ""
            STANDBY_QUORUM_TYPE: "ANY" # Quorum type can be ANY or FIRST

  tasks:
    - name: Iterate through repo role with items from hosts file
      include_role:
        name: process_vars
      with_dict: "{{ servers }}"
    - name: Iterate through repo role with items from hosts file
      include_role:
        name: setup_repo
      with_dict: "{{ servers }}"
    - name: Iterate through install role with items from hosts file
      include_role:
        name: install_dbserver
      with_dict: "{{ servers }}"
    - name: Iterate through initialize role with items from hosts file
      include_role:
        name: init_dbserver
      with_dict: "{{ servers }}"
    - name: Iterate through replication role with items from hosts file
      include_role:
        name: setup_replication
      with_dict: "{{ servers }}"
    - name: Iterate through efm install role with items from hosts file
      include_role:
        name: setup_efm
      with_dict: "{{ servers }}"
    - name: Iterate through pem install role with items from hosts file
      include_role:
        name: setup_pem
      with_dict: "{{ servers }}"
