---

- name: Ensure Postgres Data directory exists
  file:
    path: "{{ PG_DATA }}"
    owner: "{{ PG_OWNER }}"
    group: "{{ PG_GROUP }}"
    mode: 0700
    state: directory
  become: yes

- name: Ensure Postgres Log directory exists
  file:
    path: "{{ PG_LOG }}"
    owner: "{{ PG_OWNER }}"
    group: "{{ PG_GROUP }}"
    mode: 0700
    state: directory
  become: yes
  when: PG_LOG|length > 0 and not PG_DATA in PG_LOG

- name: Ensure Postgres WAL directory exists
  file:
    path: "{{ PG_WAL }}"
    owner: "{{ PG_OWNER }}"
    group: "{{ PG_GROUP }}"
    mode: 0700
    state: directory
  become: yes
  when: PG_WAL|length > 0 and not PG_DATA in PG_WAL

- name: Create Unix Socket Domain Directories
  file:
    path: "{{ line_item }}"
    owner: "{{ PG_OWNER }}"
    group: "{{ PG_GROUP }}"
    mode: 02775
    state: directory
  with_items: "{{ PG_UNIX_SOCKET_DIRECTORIES }}"
  loop_control:
    loop_var: line_item
  become: yes
  when: PG_UNIX_SOCKET_DIRECTORIES|length > 0

- name: Create hidden edb directory if not exists
  file:
    path: "{{ USER_HOMEDIR }}/.edb"
    mode: 0700
    state: directory
  delegate_to: localhost
