---
# pem credentials
os: ""
pg_version: ""

pg_user: "enterprisedb"

# pem data dir
pg_home: "/usr/edb/as{{ pg_version }}" 
pg_bin_path: "{{ pg_home }}/bin"
pg_ssl: true

pg_owner: "enterprisedb"
pg_database: "edb"

# unix socket domain directories
pg_unix_socket_directories:
   - "/var/run/edb"
     #
# postgres port
pg_port: 5444

# postgres service
pg_service: "edb-as-{{ pg_version }}"
# pem server packages
pem_server_packages:
      - edb-pem-server
