---

- name: Install Additional Python Packages
  yum:
    name:
      - python-pip
      - python-psycopg2
      - python-ipaddress
    state: present
  become: yes

- name: Install EPAS Packages
  yum:
    name:
      - edb-as{{ PG_VERSION }}-server
      - edb-as{{ PG_VERSION }}-server-core
      - edb-as{{ PG_VERSION }}-server-edb-modules
      - edb-as{{ PG_VERSION }}-server-contrib
      - edb-as{{ PG_VERSION }}-server-libs
      - edb-as{{ PG_VERSION }}-server-client
      - edb-as{{ PG_VERSION }}-server-llvmjit
      - edb-as{{ PG_VERSION }}-server-sslutils
      - edb-as{{ PG_VERSION }}-server-indexadvisor
      - edb-as{{ PG_VERSION }}-server-sqlprofiler
      - edb-as{{ PG_VERSION }}-server-sqlprotect
      - edb-as{{ PG_VERSION }}-server-sslutils
    state: present
  become: yes
