---
- name: Stop the PG service if it's running
  systemd:
      name: edb-as-{{ PG_VERSION }}
      state: stopped
  become: yes
  ignore_errors: true

- name: Remove Additional Python Packages
  yum:
    name:
      - python-pip
      - python-psycopg2
      - python-ipaddress
    state: removed
  become: yes

- name: Remove EPAS Packages
  yum:
    name:
      - edb-as{{ PG_VERSION }}-server
      - edb-as{{ PG_VERSION }}-server-core
      - edb-as{{ PG_VERSION }}-server-edb-modules
      - edb-as{{ PG_VERSION }}-server-contrib
      - edb-as{{ PG_VERSION }}-server-libs
      - edb-as{{ PG_VERSION }}-server-client
      - edb-as{{ PG_VERSION }}-server-llvmjit
      - edb-as{{ PG_VERSION }}-server-sslutils
      - edb-as{{ PG_VERSION }}-server-indexadvisor
      - edb-as{{ PG_VERSION }}-server-sqlprofiler
      - edb-as{{ PG_VERSION }}-server-sqlprotect
    state: removed
  become: yes
