---

- name: Install required dependencies
  yum:
    name:
      - glibc-common
      - ca-certificates
      - python-pycurl
      - libselinux-python
      - python-psycopg2
      - python-ipaddress
    state: present
  become: yes

- name: Install Postgres
  yum:
    name:
      - postgresql{{ PG_VERSION }}-server
      - postgresql{{ PG_VERSION }}
    state: present
  become: yes
