---

- name: Set force_install based on the user input
  set_fact:
    force_install: "{{ hostvars[inventory_hostname].force_install }}"
  when: hostvars[inventory_hostname].force_install is defined
  register: output

# Display details of Node being processed

- name: Remove Postgres packages on CentOS7 or RHEL7
  block:
    - include_tasks: "{{ pg_type }}_rhel7_rm_install.yml"
  when:
    - force_install
    - os in ['CentOS7', 'RHEL7']
  become: yes

- name: Remove Postgres packages on CentOS8 or RHEL8
  block:
    - include_tasks: "{{ pg_type }}_rhel8_rm_install.yml"
  when:
    - force_install
    - os in ['CentOS8', 'RHEL8']
  become: yes

- name: Install and Configure Postgres on CentOS7 or RHEL7
  block:
    - include_tasks: "{{ pg_type }}_rhel7_install.yml"
  become: yes
  when: os in ['CentOS7', 'RHEL7']

- name: Install and Configure Postgres on CentOS8 or RHEL8
  block:
    - include_tasks: "{{ pg_type }}_rhel8_install.yml"
  become: yes
  when: os in ['CentOS8', 'RHEL8']

- name: Reset force_install based on the user input
  set_fact:
    force_install: false
