---

- name: Install Postgres
  dnf:
    name:
      - glibc-common
      - ca-certificates
      - python3-pycurl
      - libselinux-python
      - python3-psycopg2
      - postgresql{{ pg_version }}
      - postgresql{{ pg_version }}-server
      - postgresql{{ pg_version }}-contrib
      - sslutils_{{ pg_version }}
    state: present
  become: yes
