---

- name: Set PG_PEM_AGENT_PASSWORD if not provided
  set_fact:
    PG_PEM_AGENT_PASSWORD: "{{ lookup('password', '{{ USER_HOMEDIR }}/.edb/{{ PG_PEM_AGENT_USER }}_pass chars=ascii_letters') }}"
  when: PG_PEM_AGENT_PASSWORD|length < 1
  become: no
  delegate_to: localhost

- name: Create EDB pem agent role if not exists
  postgresql_user:
    name: "{{ PG_PEM_AGENT_USER }}"
    password: "{{ PG_PEM_AGENT_PASSWORD }}"
    login_user: "{{ PG_OWNER }}"
    login_unix_socket: "{{ PG_UNIX_SOCKET_DIRECTORIES[0] }}"
    db: "{{ PG_DATABASE }}"
    port: "{{ PG_PORT }}"
    state: present
  no_log: True
  become: yes
  become_user: "{{ PG_OWNER }}"

- name: Assign pg_monitor to PG_PEM_AGENT_USER
  postgresql_membership:
    group: pg_monitor
    target_roles: "{{ PG_PEM_AGENT_USER }}"
    login_user: "{{ PG_OWNER }}"
    login_unix_socket: "{{ PG_UNIX_SOCKET_DIRECTORIES[0] }}"
    db: "{{ PG_DATABASE }}"
    port: "{{ PG_PORT }}"
    state: present
  become: yes
  become_user: "{{ PG_OWNER }}"
