---

- name: Set PG_PEM_ADMIN_PASSWORD if not provided
  set_fact:
    PG_PEM_ADMIN_PASSWORD: "{{ lookup('password', '{{ USER_HOMEDIR }}/.edb/{{ PG_PEM_ADMIN_USER }}_pass chars=ascii_letters') }}"
  when: PG_PEM_ADMIN_PASSWORD|length < 1
  become: no
  delegate_to: localhost

- name: Create EDB pem superuser role if not exists
  postgresql_user:
    name: "{{ PG_PEM_ADMIN_USER }}"
    password: "{{ PG_PEM_ADMIN_PASSWORD }}"
    role_attr_flags: SUPERUSER,CREATEDB,CREATEROLE
    login_user: "{{ PG_OWNER }}"
    login_unix_socket: "{{ PG_UNIX_SOCKET_DIRECTORIES[0] }}"
    db: "{{ PG_DATABASE }}"
    port: "{{ PG_PORT }}"
    state: present
  no_log: True
  become: yes
  become_user: "{{ PG_OWNER }}"
