---

- name: Stopped pemagent
  systemd:
    name: "{{ PEM_AGENT_SERVICE }}"
    daemon_reload: yes
    state: stopped
  become: yes
  ignore_errors: yes

- name: Remove pem ceritficate directory
  file:
    path: /root/.pem
    state: absent
  become: yes

- name: Remove agent.cfg
  file:
    path: "{{ PEM_AGENT_BIN_PATH }}/../etc/agent.cfg"
    state: absent
  become: yes

- name: Remove worker.log
  file:
    path: "/var/log/pem/worker.log"
    state: absent
  become: yes
