---
- name: Create PgBouncer system group {{ pgbouncer_group }}
  group:
    name: "{{ pgbouncer_group }}"
    state: present
  delegate_to: "{{ item.value.public_ip }}"

- name: Create PgBouncer system user {{ pgbouncer_user }}
  user:
    name: "{{ pgbouncer_user }}"
    system: true
    group: "{{ pgbouncer_group }}"
    state: present
    create_home: false
  delegate_to: "{{ item.value.public_ip }}"

- name: Create configuration directories
  file:
    path: "{{ dir_item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - "{{ pgbouncer_config_file | dirname }}"
    - "{{ pgbouncer_databases_file | dirname }}"
    - "{{ pgbouncer_systemd_unit_file | dirname }}"
  loop_control:
    loop_var: dir_item
  delegate_to: "{{ item.value.public_ip }}"

- name: Create logging directory {{ pgbouncer_log_file | dirname }}
  file:
    path: "{{ pgbouncer_log_file | dirname }}"
    state: directory
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0755
  delegate_to: "{{ item.value.public_ip }}"

- name: Create running directory {{ pgbouncer_pid_file | dirname }}
  file:
    path: "{{ pgbouncer_pid_file | dirname }}"
    state: directory
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0700
  delegate_to: "{{ item.value.public_ip }}"

- name: Generate PgBouncer configuration file {{ pgbouncer_config_file }}
  template:
    backup: yes
    dest: "{{ pgbouncer_config_file }}"
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    src: ./templates/pgbouncer.ini.template
  delegate_to: "{{ item.value.public_ip }}"

- name: Create empty databases file {{ pgbouncer_databases_file }}
  copy:
    content: "[databases]\n"
    dest: "{{ pgbouncer_databases_file }}"
    force: no
    group: "{{ pgbouncer_group }}"
    owner: "{{ pgbouncer_user }}"
    mode: 0600
  delegate_to: "{{ item.value.public_ip }}"

- name: Create empty authentication file {{ pgbouncer_auth_file }}
  copy:
    content: ""
    dest: "{{ pgbouncer_auth_file }}"
    force: no
    group: "{{ pgbouncer_group }}"
    owner: "{{ pgbouncer_user }}"
    mode: 0600
  delegate_to: "{{ item.value.public_ip }}"

- name: Generate PgBouncer systemd unit file {{ pgbouncer_systemd_unit_file }}
  template:
    backup: yes
    dest: "{{ pgbouncer_systemd_unit_file }}"
    src: ./templates/pgbouncer.unit.conf.template
  delegate_to: "{{ item.value.public_ip }}"

- name: Open TCP port {{ pgbouncer_listen_port }}
  firewalld:
    port: "{{ pgbouncer_listen_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: true
  delegate_to: "{{ item.value.public_ip }}"
  when: os in ['CentOS8', 'CentOS7', 'RHEL7', 'RHEL8']

- name: Stop PgBouncer service
  systemd:
    name: pgbouncer
    state: stopped
  delegate_to: "{{ item.value.public_ip }}"

- name: Enable and start PgBouncer service
  systemd:
    name: pgbouncer
    enabled: true
    daemon_reload: yes
    state: started
  delegate_to: "{{ item.value.public_ip }}"
