---
- name: Create optional Databases
  postgresql_db:
    name: "{{ line_item.name }}"
    owner: "{{ line_item.owner | default(PG_SUPERUSER) }}"
    encoding: "{{ PG_ENCODING }}"
    lc_collate: "{{ PG_LOCALE }}.{{ PG_ENCODING }}"
    lc_ctype: "{{ PG_LOCALE }}.{{ PG_ENCODING }}"
    port: "{{ PG_PORT }}"
    template: "template0"
    maintenance_db: "{{ PG_DATABASE }}"
    state: present
    login_user: "{{ PG_OWNER }}"
  become: yes
  become_user: "{{ PG_OWNER }}"
  with_items: "{{ PG_DATABASES }}"
  loop_control:
    loop_var: line_item
  when: PG_DATABASES|length > 0
