---

- name: GRANT execute privilege to users
  postgresql_privs:
    type: "{{ line_item.type }}"
    state: "{{ line_item.grant }}"
    privs: "{{ line_item.privileges }}"
    schema: "{{ line_item.schema }}"
    objs: "{{ line_item.objects }}"
    roles: "{{ line_item.roles }}"
    db: "{{ line_item.database }}"
    login_user: "{{ PG_OWNER }}"
    login_unix_socket: "{{ PG_UNIX_SOCKET_DIRECTORIES[0] }}"
    port: "{{ PG_PORT }}"
  become: yes
  become_user: "{{ PG_OWNER }}"
  with_items: "{{ PG_GRANT_PRIVILEGES }}"
  loop_control:
    loop_var: line_item
  when: PG_GRANT_PRIVILEGES|length > 0

- name: GRANT role to users
  postgresql_membership:
    group: "{{ line_item.role }}"
    target_role: "{{ line_item.user }}"
    state: "{{ line_item.grant }}"
    db: "{{ PG_DATABASE }}"
    login_user: "{{ PG_OWNER }}"
    login_unix_socket: "{{ PG_UNIX_SOCKET_DIRECTORIES[0] }}"
    port: "{{ PG_PORT }}"
  no_log: true
  become: yes
  become_user: "{{ PG_OWNER }}"
  with_items: "{{ PG_GRANT_ROLES }}"
  loop_control:
    loop_var: line_item
  when: PG_GRANT_ROLES|length > 0
