---

- name: Enumerate disks
  command: lsblk --raw --noheadings --nodeps --output NAME
  register: block_devices
  check_mode: no
  changed_when: false

- name: Update the block devices
  shell: |
    /bin/echo 4096 > /sys/block/{{ line_item }}/queue/read_ahead_kb
  with_items: "{{ block_devices.stdout_lines }}"
  loop_control:
    loop_var: line_item
  changed_when: false

- name: Ensure /etc/tuned/edb directory exists
  file:
    path: "/etc/tuned/edb"
    mode: 0700
    state: directory
  become: yes

- name: Create tuned.conf for Postgres
  lineinfile:
    path: "/etc/tuned/edb/tuned.conf"
    line: "{{ line_item }}"
    create: yes
  with_items:
    - "[main]"
    - "summary=Tuned profiles for EnterpriseDB Postgres Advanced Server"
    - "[cpu]"
    - "governor=performance"
    - "energy_perf_bias=performance"
    - "min_perf_pct=100"
    - "[disk]"
    - "readahead=>4096"
    - "[sysctl]"
    - "vm.overcommit_memory=2"
    - "vm.swappiness=1"
    - "vm.dirty_ratio=30"
    - "vm.dirty_background_ratio=10"
    - "[vm]"
    - "transparent_hugepages=never"
  loop_control:
      loop_var: line_item
  register: edb_tuned
  become: yes

- name: Enable the tuned
  systemd:
    name: tuned
    daemon_reload: yes
    state: started
  become: yes

- name: Load the new settings using tuned
  shell: |
    /sbin/tuned-adm profile edb && echo "successful" || echo "failed"
  args:
    executable: /bin/bash
  register: output
  changed_when: "'successful' in output.stdout"
  failed_when: "'failed' in output.stdout"
  when: edb_tuned.changed
  become: yes
