---

- name: Stop PG service if running
  systemd:
    name: "{{ PG_SERVICE }}"
    state: stopped
  become: yes

- name: Remove postgres data directory if exists
  file:
    path: "{{ PG_DATA }}"
    state: absent
  become: yes

- name: Remove postgres log directory if exists
  file:
    path: "{{ PG_LOG }}"
    state: absent
  become: yes
  when: PG_LOG|length > 0

- name: Remove postgres WAL directory exists
  file:
    path: "{{ PG_WAL }}"
    state: absent
  become: yes
  when: PG_WAL|length > 0

- name: Remove postgres /etc/edb/certs/.created_ssl  directory exists
  file:
    path: "{{ PG_SSL_DIR }}/.created_ssl"
    state: absent
  become: yes
