---

- name: Create Postgres extensions
  postgresql_ext:
    name: "{{ line_item.name }}"
    port: "{{ PG_PORT }}"
    db: "{{ line_item.database }}"
    cascade: yes
    state: present
    login_user: "{{ PG_OWNER }}"
    login_unix_socket: "{{ PG_UNIX_SOCKET_DIRECTORIES[0] }}"
  become: yes
  become_user: "{{ PG_OWNER }}"
  with_items: "{{ PG_EXTENSIONS }}"
  loop_control:
    loop_var: line_item
  when: PG_EXTENSIONS|length > 0
