---
# Tasks file for edb.postgres.install Role

# Reference EPAS Variables
- name: Reference EPAS Variables
  include_vars: edb-epas.yml
  when: PG_TYPE == 'EPAS'

- name: Reference EPAS Variables
  include_vars: edb-pg.yml
  when: PG_TYPE == 'PG'

# Display if the Operating System is supported
- name: Display support for Operating System
  block:
    - debug:
        msg: "Operating System = {{ OS }} not supported. Only 'CentOS7' and 'RHEL7'."
  when: OS != 'CentOS7' and OS != 'RHEL7'

# Display if the Database Version is not supported
- name: Display supported versions for Database Engine
  block:
    - debug:
        msg: "Database Engine Version = {{ PG_VERSION }} not supported."
  when: PG_VERSION != '10' and PG_VERSION != '11' and PG_VERSION != '12'

# End Playbook if the Type of Install, Operating System or Postgres Version are not supported
- meta: end_play
  when: OS != 'CentOS7' and OS != 'RHEL7' or
        PG_VERSION != '10' and PG_VERSION != '11' and PG_VERSION != '12'

# Configure Variables
- name: Display current Node to Install
  block:
    - debug:
        msg:
            "Operating System = {{ OS }}:
             Postgres Version = {{ PG_VERSION }},
             Database Engine = {{ PG_TYPE }},
             Public IP = {{ item.value.public_ip }}"

# Setting variables available for all nodes
# Any of the variables existing can be updated and configured
- meta: flush_handlers

- name: Set Node Type
  set_fact:
    NODE_TYPE: "{{ item.value.node_type }}"
  register: output

- name: set FORCE_INITIALIZE based on the user input
  set_fact:
      FORCE_INITIALIZE: "{{ item.value.force_initialize }}"
  when: item.value.force_initialize is defined
  register: output

# main blog for tasks
- name: Force cleanup based on force_initialize
  block:
    - include_tasks: C07-RH07-rm-initialize.yml
  when: FORCE_INITIALIZE and NODE_TYPE == 'primary'
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Check and configure the primary node
  block:
    - import_tasks: C07-RH07-check-service.yml
    - import_tasks: C07-RH07-create-directories.yml
    - import_tasks: C07-RH07-initdb-cmd.yml
    - import_tasks: C07-RH07-update-service.yml
    - import_tasks: C07-RH07-configure-node.yml
  become: yes
  when: NODE_TYPE == 'primary'
  delegate_to: "{{ item.value.public_ip }}"

- name: Configure SSL based on PG_SSL parameter
  block:
    - import_tasks: C07-RH07-ssl-configure.yml
  become: yes
  when: NODE_TYPE == 'primary' and PG_SSL
  delegate_to: "{{ item.value.public_ip }}"

- name: Apply any user defined settings, users, databases and configurations
  block:
    - import_tasks: C07-RH07-users.yml
    - import_tasks: C07-RH07-databases.yml
    - import_tasks: C07-RH07-update-conf-hba.yml
  when: NODE_TYPE == 'primary'
  delegate_to: "{{ item.value.public_ip }}"

- name: Reset FORCE/SKIP_INITIALIZE based on the user input
  set_fact:
      FORCE_INITIALIZE: false
  register: output
