---
# tasks file for edb.postgres.install role

# reference epas variables
- name: Reference pg_type variables
  include_vars: "{{ pg_type }}.yml"

- name: Reference ssl variables
  include_vars: edb-ssl.yml
  when: pg_ssl

# display if the operating system is supported
- name: Display support for operating system
  block:
    - debug:
        msg: "operating system = {{ os }} not supported."
  when: os not in supported_os

# display if the database version is not supported
- name: Display supported versions for database engine
  block:
    - debug:
        msg: "database engine version = {{ pg_version }} not supported."
  when: pg_version|int not in supported_pg_version

# end playbook if the type of install, operating system or postgres version are not supported
- meta: end_play
  when: os not in supported_os or
        pg_version|int not in supported_pg_version

- name: Gather the host and information for /etc/hosts
  set_fact:
    etc_hosts_lists: "{{ etc_hosts_lists + [item.value.private_ip + ' ' + item.value.hostname] }}"
  when: item.value.hostname is defined
  with_dict: "{{ servers }}"

- name: Include the init_dbserver
  include_tasks: init_dbserver.yml
  when: item.value.node_type in ['primary','pemserver']
  with_dict:  "{{ servers }}"

- name: Reset etc_hosts_list variable
  set_fact:
    etc_hosts_lists: []
