---
# tasks file for the init_dbserver role

# reference epas variables
- name: Reference pg_type variables
  include_vars: "{{ pg_type }}.yml"

- name: Reference ssl variables
  include_vars: edb-ssl.yml
  when: pg_ssl

# Check if the Operating System is supported
- name: Check support for Operating System
  fail:
    msg: "Operating System = {{ os }} not supported."
  when: os not in supported_os

# Check if the Database Version is supported
- name: Check supported versions for Database engine
  fail:
    msg: "Database Engine Version = {{ pg_version }} not supported.
          Supported versions are {{ supported_pg_version }}"
  when: pg_version|int not in supported_pg_version

- name: Gather the host and information for /etc/hosts
  set_fact:
    etc_hosts_lists: "{{ etc_hosts_lists + [item.value.private_ip + ' ' + item.value.hostname] }}"
  when:
    - item.value.hostname is defined
    - item.value.node_type in supported_node_type
  with_dict: "{{ servers }}"

- name: Include the init_dbserver
  include_tasks: init_dbserver.yml
  when: item.value.node_type in supported_node_type
  with_dict:  "{{ servers }}"

- name: Reset etc_hosts_list variable
  set_fact:
    etc_hosts_lists: []
