---
- name: Verify pg_wal and accordingly add the in the initdb
  set_fact:
    pg_initdb_options: "{{ pg_initdb_options + ' --waldir=' + pg_wal }}"
  when: pg_wal|length > 0  and not pg_data in pg_wal

- name: Initialize database postgres service
  shell: |
    export PGSETUP_INITDB_OPTIONS="{{ pg_initdb_options }}"
    {{ pg_initdb }}
  args:
    creates: "{{ pg_data }}/PG_VERSION"
  become: yes

- name: Copy the postgresql.conf.template to the server
  template:
    src: postgresql.conf.template
    dest: "{{ pg_data }}/postgresql.conf"
    owner: "{{ pg_owner }}"
    group: "{{ pg_group }}"
    mode: 0600
  become: yes

- name: Start the pg_service
  systemd:
    name: "{{ pg_service }}"
    daemon_reload: yes
    state: started
  become: yes
