---

- name: Generate the pg_superuser_password
  include_role:
    name: manage_dbserver
    tasks_from: generate_password
  vars:
    input_user: "{{ pg_superuser }}"
    input_password: "{{ pg_superuser_password }}"
  no_log: true
  when: pg_superuser_password|length < 1

- name: Set pg_superuser_password
  set_fact:
     pg_superuser_password: "{{ input_password }}"
  when: pg_superuser_password|length < 1

- name: Set postgres superuser's database cluster password
  include_role:
    name: manage_dbserver
    tasks_from: manage_users
  vars:
    pg_users:
       - name: "{{ pg_superuser }}"
         pass: "{{ pg_superuser_password }}"

- name: Set postgres primary_slot_name
  include_role:
    name: manage_dbserver
    tasks_from: manage_postgres_params
  vars:
    pg_postgres_conf_params:
        - name: primary_slot_name
          value: "{{ item.key | regex_replace('[^a-zA-Z0-9_]', '_') }}"
  when:
    - pg_version|int > 11
