---

- name: Set the os variable
  set_fact:
    os: "{{ ansible_distribution | replace('RedHat', 'RHEL') }}{{ ansible_distribution_major_version }}"

- name: Include the tuned package installation tasks
  include_tasks: install_tuned.yml

- name: Include tuned setting up tasks
  include_tasks: setup_tuned.yml
