---
# Merge pgpool2_default_configuration and pgpool2_configuration
- set_fact:
    pgpool2_configuration: >-
      {{ pgpool2_configuration | default([]) + [
          merge_item |
          combine(
            pgpool2_configuration |
            selectattr('key', 'match', merge_item.key) |
            list
          )
        ] }}
  loop: "{{ pgpool2_default_configuration }}"
  loop_control:
    loop_var: merge_item

# Generate configuration parameters dictionary
- name: Generate configuration parameters dictionary
  set_fact:
    config_dict: >-
      {{ config_dict|default({}) | combine( {ci.key: ci.value} ) }}
  with_items: "{{ pgpool2_configuration }}"
  loop_control:
    loop_var: ci
  when:
    - ci.state == 'present'

- name: Create pgpoolII system group {{ pgpool2_group }}
  group:
    name: "{{ pgpool2_group }}"
    state: present

- name: Create pgpoolII system user {{ pgpool2_user }}
  user:
    name: "{{ pgpool2_user }}"
    system: true
    group: "{{ pgpool2_group }}"
    state: present
    create_home: false

- name: Create configuration directory {{ pgpool2_configuration_file | dirname }}
  file:
    path: "{{ pgpool2_configuration_file | dirname }}"
    state: directory
    owner: "{{ pgpool2_user }}"
    group: "{{ pgpool2_group }}"
    mode: 0755

- name: Create logging directory {{ config_dict.logdir | default('') }}
  file:
    path: "{{ config_dict.logdir }}"
    state: directory
    owner: "{{ pgpool2_user }}"
    group: "{{ pgpool2_group }}"
    mode: 0755
  when: config_dict.logdir is defined

- name: Create running directory {{ config_dict.pid_file_name | default('') | dirname }}
  file:
    path: "{{ config_dict.pid_file_name | dirname }}"
    state: directory
    owner: "{{ pgpool2_user }}"
    group: "{{ pgpool2_group }}"
    mode: 0700
  when: config_dict.pid_file_name is defined

- name: Create oiddir directory {{ config_dict.memqcache_oiddir | default('') }}
  file:
    path: "{{ config_dict.memqcache_oiddir }}"
    state: directory
    owner: "{{ pgpool2_user }}"
    group: "{{ pgpool2_group }}"
    mode: 0700
  when: config_dict.memqcache_oiddir is defined

# Build the configuration file
- include_role:
    name: manage_pgpool2
    tasks_from: pgpool2_manage_configuration
  vars:
    pgpool2_configuration_lines: "{{ pgpool2_configuration }}"

- name: Open listening TCP port {{ config_dict.port | default('') }}
  firewalld:
    port: "{{ config_dict.port }}/tcp"
    permanent: yes
    state: enabled
    immediate: true
  when:
    - os in ['CentOS8', 'CentOS7', 'RHEL7', 'RHEL8']
    - config_dict.port is defined

- name: Open PCP TCP port {{ config_dict.pcp_port | default('') }}
  firewalld:
    port: "{{ config_dict.pcp_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: true
  when:
    - os in ['CentOS8', 'CentOS7', 'RHEL7', 'RHEL8']
    - config_dict.pcp_port is defined

- name: Open PCP UDP port {{ config_dict.pcp_port | default('') }}
  firewalld:
    port: "{{ config_dict.pcp_port }}/udp"
    permanent: yes
    state: enabled
    immediate: true
  when:
    - os in ['CentOS8', 'CentOS7', 'RHEL7', 'RHEL8']
    - config_dict.pcp_port is defined

- name: Open Watchdog TCP port {{ config_dict.wd_port | default('') }}
  firewalld:
    port: "{{ config_dict.wd_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: true
  when:
    - os in ['CentOS8', 'CentOS7', 'RHEL7', 'RHEL8']
    - config_dict.wd_port is defined
    - config_dict.use_watchdog == 'on'

- name: Open Watchdog UDP port {{ config_dict.wd_port | default('') }}
  firewalld:
    port: "{{ config_dict.wd_port }}/udp"
    permanent: yes
    state: enabled
    immediate: true
  when:
    - os in ['CentOS8', 'CentOS7', 'RHEL7', 'RHEL8']
    - config_dict.wd_port is defined
    - config_dict.use_watchdog == 'on'

- name: Open Watchdog heartbeat TCP port {{ config_dict.wd_heartbeat_port | default('') }}
  firewalld:
    port: "{{ config_dict.wd_heartbeat_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: true
  when:
    - os in ['CentOS8', 'CentOS7', 'RHEL7', 'RHEL8']
    - config_dict.wd_heartbeat_port is defined
    - config_dict.use_watchdog == 'on'

- name: Open Watchdog heartbeat UDP port {{ config_dict.wd_heartbeat_port | default('') }}
  firewalld:
    port: "{{ config_dict.wd_heartbeat_port }}/udp"
    permanent: yes
    state: enabled
    immediate: true
  when:
    - os in ['CentOS8', 'CentOS7', 'RHEL7', 'RHEL8']
    - config_dict.wd_heartbeat_port is defined
    - config_dict.use_watchdog == 'on'

- name: Create pgpoolII systemd directory
  file:
    path: "{{ pgpool2_systemd_unit_file | dirname }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0700
  when:
    - pg_type == 'PG'

- name: Generate pgpoolII systemd unit file
  template:
    backup: yes
    dest: "{{ pgpool2_systemd_unit_file }}"
    src: ./templates/pgpool-II.unit.conf.template
    mode: 0644
  when:
    - pg_type == 'PG'

- name: Stop pgpoolII service
  systemd:
    name: "{{ pgpool2_service_name }}"
    state: stopped

- name: Enable and start pgpoolII service
  systemd:
    name: "{{ pgpool2_service_name }}"
    enabled: true
    daemon_reload: yes
    state: started
