---
- name: Define pg_basebackup command.
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' -D ' + pg_data }}"

- name: Verify pg_wal and accordingly add the in the pg_basebackup
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' --waldir=' + pg_wal }}"
  when: pg_wal|length > 0  and not pg_data in pg_wal

- name: Add slot_name in pg_basebackup
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' --slot=' }}{{ item.key | regex_replace('[^a-zA-Z0-9_]', '_') }}"

- name: Set replication user information
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' --username=' + pg_replication_user }}"
  when: pg_replication_user|length > 0

- name: Set host and port
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' --host=' + primary_private_ip + ' --port=' + pg_port }}"
  when: not use_hostname

- name: Set host and port
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' --host=' + primary_host_name + ' --port=' + pg_port }}"
  when: use_hostname

- name: Use other supplied options if given
  set_fact:
    pg_basebackup: "{{ pg_basebackup + ' ' + pg_basebackup_options }}"
  when: pg_basebackup_options|length > 0
