---

- name: Generate the pg_replication_user_password
  include_role:
    name: manage_dbserver
    tasks_from: generate_password
  vars:
    input_user: "{{ pg_replication_user }}"
    input_password: "{{ pg_replication_user_password }}"
  no_log: true
  when: pg_replication_user_password|length < 1

- name: Set pg_replication_user_password
  set_fact:
     pg_replication_user_password: "{{ input_password }}"
  when: pg_replication_user_password|length < 1

- name: Set postgres replication users's database cluster password
  include_role:
    name: manage_dbserver
    tasks_from: manage_users
  vars:
    pg_users:
       - name: "{{ pg_replication_user }}"
         pass: "{{ pg_replication_user_password }}"
         role_attr_flags: replication

- name: Grant minimum privileges to replication user for rewind
  include_role:
    name: manage_dbserver
    tasks_from: manage_privileges
  vars:
    pg_grant_privileges:
      - type: function
        privileges: execute
        schema: pg_catalog
        objects: "pg_ls_dir(text:boolean:boolean),pg_stat_file(text:boolean)"
        roles: "{{ pg_replication_user }}"
        database: "{{ pg_database }}"
      - type: function
        privileges: execute
        schema: pg_catalog
        objects: "pg_read_binary_file(text),pg_read_binary_file(text:bigint:bigint:boolean)"
        roles: "{{ pg_replication_user }}"
        database: "{{ pg_database }}"

- name: Update the pgpass with replication users password
  include_role:
    name: manage_dbserver
    tasks_from: manage_pgpass
  vars:
    pg_pgpass_values:
        - user: "{{ pg_replication_user }}"
          password: "{{ pg_replication_user_password }}"
          create: yes
  no_log: yes

- name: Update primary hba config
  include_role:
    name: manage_dbserver
    tasks_from: manage_hba_conf
  vars:
    pg_hba_ip_addresses: "{{ pg_allow_ip_addresses }}"

- name: Create physical slots of the standbys
  include_role:
    name: manage_dbserver
    tasks_from: manage_slots
  vars:
    pg_slots: "{{ standby_physical_slots }}"
