---
# configure variables
- name: Display details of node to configure
  block:
    - debug:
        msg:
            "operating system = {{ os }}:
             postgres version = {{ pg_version }},
             public ip = {{ item.value.public_ip }},
             standby_names = {{ standby_names }}"

- name: Set force_replication based on the user input
  set_fact:
      force_replication: "{{ item.value.force_replication }}"
  when: item.value.force_replication is defined
  register: output

- name: Force cleanup based on force_replication
  block:
    - include_tasks: rm_replication.yml
  when: force_replication
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

# postgres

- name: Update etc_hosts based on use_hostname
  block:
    - import_tasks: linux_update_etc_hosts.yml
  become: yes
  when: use_hostname
  delegate_to: "{{ item.value.public_ip }}"

- name: Build standby service check
  block:
    - import_tasks: create_directories.yml
    - import_tasks: pg_basebackup.yml
    - import_tasks: configure_node.yml
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Reset the the variables based on the user input
  set_fact:
      force_replication: false
  register: output

