---

- name: Set force install based on the user input
  set_fact:
    force_install: "{{ hostvars[inventory_hostname].force_install }}"
  when: hostvars[inventory_hostname].force_install is defined
  register: output

- name: Cleanup the repos based on force_install
  block:
    - include_tasks: "{{ pg_type }}_rhel_rm_repos.yml"
  when: force_install
  become: yes

- name: Install Postgres RPM repositories
  block:
    - include_tasks: "{{ pg_type }}_rhel_setuprepos.yml"
  become: yes

- name: Reset force install based on the user input
  set_fact:
    force_install: false
