- name: Set force install based on the user input
  set_fact:
      force_install: "{{ item.value.force_install }}"
  when: item.value.force_install is defined
  register: output

# display details of ip address being processed
- name: Details of node being processed
  block:
    - debug:
        msg: "operating system = {{ os }},
             database engine = {{ pg_type }},
             public ip = {{ item.value.public_ip }}"


- name: Cleanup the repos based on force_install
  block:
    - include_tasks: "{{ pg_type }}_rhel_rm_repos.yml"
  when:  force_install
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Install and configure postgres on centos7 or rhel7
  block:
    - include_tasks: "{{ pg_type }}_rhel_setuprepos.yml"
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Reset force install based on the user input
  set_fact:
      force_install: false
