---
- name: Create hidden pass directory if not exists
  file:
    path: "{{ pass_dir }}"
    mode: 0700
    state: directory
  become: no
  delegate_to: localhost

- name: Create passfile location
  set_fact:
    passfile: "{{ pass_dir }}/{{ inventory_hostname }}_{{ input_user }}_pass"
  when: input_user|length > 0
  become: no
  delegate_to: localhost

- name: Generate password or copy the password from pass file
  set_fact:
    input_password: "{{ lookup('password', passfile + ' chars=ascii_letters') }}"
  when: input_password|length < 1
  become: no
  delegate_to: localhost

- name: Make sure file is has permission for owner only
  file:
    path: "{{ passfile }}"
    mode: 0600
  when: passfile|length > 0
  become: no
  delegate_to: localhost
