---
pgpool2_vip: ""
pgpool2_vip_dev: ""
pgpool2_watchdog: false

# Enable load balancing
pgpool2_load_balancing: true

# Postgres user that pgpool2 will use to check Postgres nodes roles in load
# balance mode
pgpool2_sr_check_user: "pgpool2"
# If empty or not defined, a random password will be generated
pgpool2_sr_check_password: ""

pgpool2_configuration: []

supported_os:
  - CentOS7
  - CentOS8
  - RHEL7
  - RHEL8

supported_pg_version:
  - 10
  - 11
  - 12
  - 13

supported_node_type:
  - pgpool2

supported_pgpool2_version:
  - 4.1
