---

- name: Include the HBA file update tasks
  include_tasks: update_pg_hba.yml

- name: Include Postgres configuration for TPROC-C
  include_tasks: configure_postgres_params.yml

- name: Include HammerDB installation
  include_role:
    name: setup_hammerdbserver
    tasks_from: install_hammerdb

- name: Include Touchstone installation
  include_role:
    name: setup_touchstone
    tasks_from: main

- name: Create TPROC-C loader.tcl
  template:
    dest: loader.tcl
    src: ./templates/loader.tcl.template
    mode: 0644
  become: no

- name: Create TPROC-C load script
  template:
    src: ./templates/load-tproc-c.template
    dest: /usr/local/bin/load-tproc-c
    mode: 0755
  become: yes
