---

- name: Install packages required for installing HammerDB
  ansible.builtin.package:
    name:
      - curl
  become: true
  failed_when: false

- name: Download HammerDB
  ansible.builtin.get_url:
    url: "{{ hammerdb_url }}/v{{ hammerdb_version }}/{{ hammerdb_filename }}"
    dest: "{{ ansible_user_dir }}/{{ hammerdb_filename }}"
    mode: '0644'

- name: Install HammerDB
  ansible.builtin.unarchive:
    src: "{{ ansible_user_dir }}/{{ hammerdb_filename }}"
    dest: "{{ ansible_user_dir }}"
    remote_src: true
