namespace: "dougortiz"
name: "edb_ansible_postgres"
version: "1.0.4"
readme: "README.md"
authors:
- "Doug Ortiz"
- "Vibhor Kumar (Reviewer)"
dependencies:
description: This Ansible Galaxy Role sets up and configures the repositories from which packages will be retrieved for any Postgres or EnterpriseDB Postgresql Advanced Server installations.
license:
- "BSD-3-Clause"
license_file: ''
tags: 
- database
- postgresql
- postgres
- edb
- edb_postgres_repo
dependencies: {}
repository: "https://github.com/EnterpriseDB/edb-ansible/tree/master/edb_ansible_postgres"
documentation: "https://github.com/EnterpriseDB/edb-ansible/tree/master/edb_ansible_postgres/README.md"
homepage: "https://github.com/EnterpriseDB/edb-ansible/tree/master/edb_ansible_postgres"
issues: "https://github.com/EnterpriseDB/edb-ansible/issues"
