---
OS: ""
PG_TYPE: "EPAS"
PG_VERSION: "12"

FORCE_INITIALIZE: false

USER_HOMEDIR: "~/"

PG_SSL: True
PG_SSL_DIR: "/etc/edb/certs"
PG_SSL_GENERATE: True
# Postgres Settings
PG_WAL: ""
PG_DATA: "/var/lib/edb/as{{ PG_VERSION }}/data"
PG_DEFAULT_DATA: "/var/lib/edb/as{{ PG_VERSION }}/data"
PG_ENCODING: "UTF-8"
# Encoding details
PG_LOCALE: "en_US"

# Log directory and Filename
PG_LOG: ""
PG_LOG_FILENAME: "postgresql.log"

# Databases
PG_DATABASES: []
# List of Databases Example
#PG_DATABASES:
# - name: pgdatabase

# Users
PG_USERS: []
# List of Users Example
#PG_USERS:
#- name: pg1
#  pass: pg1
#  encrypted: yes

# Postgres Service
PG_SERVICE: "edb-as-{{ PG_VERSION }}"

# Required & optional directories
PG_USER_HOME: "/var/lib/edb"
PG_BIN_PATH: "/usr/edb/as{{ PG_VERSION }}/bin"

# Unix socket domain directories
PG_UNIX_SOCKET_DIRECTORIES:
  - "/var/run/edb"

# Postgres Port
PG_PORT: 5444

# Postgres Database
PG_DATABASE: "postgres"

# Postgres User
PG_OWNER: "enterprisedb"
PG_GROUP: "enterprisedb"

# Postgres SuperUser
PG_SUPERUSER: "enterprisedb"
PG_RANDOM_PASSWORD: false
PG_SUPERUSER_PASSWORD: ""
PG_INITDB: "{{ PG_BIN_PATH }}/initdb --auth=peer --auth-host=scram-sha-256"
PG_INITDB_OPTIONS: " --data-checksums "


# Global configuration options that will be set via ALTER SYSTEM in postgresql.auto.conf
PG_POSTGRES_DEFAULT_CONF_PARAMS:
  - {name: "unix_socket_directories", value: "{{ PG_UNIX_SOCKET_DIRECTORIES | join(',') }}"}
  - {name: "listen_addresses", value: "*" }
  - { name: wal_level, value: replica }
  - { name: max_wal_senders, value: 10 }
  - { name: hot_standby, value: "on" }
  - { name: max_replication_slots, value: 10 }
PG_POSTGRES_CONF_PARAMS: ""
PG_ALLOW_IP_ADDRESSES: ""
