---
- hosts: localhost
  #vars:
  #  ansible_python_interpreter: /usr/bin/python2
  name: Install, Configure, Initialize and Replicate EPAS 12 and EFM 10 on Instances
  #connection: local
  become: true
  gather_facts: false

  collections:
    - edb_devops.edb_postgres

  vars_files:
    - hosts.yml

  # Initializing internal variables
  vars:
    PEM_SERVER_PRIVATE_IP: ""
    PRIMARY_PRIVATE_IP: ""
    PRIMARY_PUBLIC_IP: ""
    STANDBY_NAMES: []
    ALL_NODE_IPS: []
    EFM_NODES_PRIVATE_IP: []
    EFM_NODES_PUBLIC_IP: []

  # Internal processing purposes only
  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        OS: "CentOS7"
        PG_VERSION: "12"
        PG_TYPE: "PG"
        PG_DATA: "/data/pgdata"
        PG_WAL: "/data/pg_wal"
        EDB_YUM_USERNAME: ""
        EDB_YUM_PASSWORD: ""
        STANDBY_QUORUM_TYPE: "ANY"   # Quorum type can be ANY or FIRST
        ALL_NODE_IPS: "{{ ALL_NODE_IPS + [item.value.private_ip] }}"
        PEM_SERVER_PRIVATE_IP: "{{ PEM_SERVER_PRIVATE_IP + item.value.private_ip if(item.value.node_type == 'pemserver') else PEM_SERVER_PRIVATE_IP }}"
        PRIMARY_PRIVATE_IP: "{{ PRIMARY_PRIVATE_IP + item.value.private_ip if(item.value.node_type == 'primary') else PRIMARY_PRIVATE_IP }}"
        PRIMARY_PUBLIC_IP: "{{ PRIMARY_PUBLIC_IP  + item.value.public_ip if(item.value.node_type == 'primary') else PRIMARY_PUBLIC_IP }}"
      with_dict: "{{ servers }}"

    - name: Gather primary and standby nodes for EFM
      set_fact:
          EFM_NODES_PRIVATE_IP: "{{ EFM_NODES_PRIVATE_IP + [item.value.private_ip] }}"
          EFM_NODES_PUBLIC_IP: "{{ EFM_NODES_PUBLIC_IP + [item.value.public_ip] }}"
      when: item.value.node_type in ['primary', 'standby']
      with_dict: "{{ servers }}"

    - name: Gather the standby names
      set_fact:
        STANDBY_NAMES: "{{ STANDBY_NAMES + [item.key] }}"
      when: item.value.node_type == 'standby'
      with_dict: "{{ servers }}"

  tasks:
    - name: Iterate through role with items from hosts file
      include_role:
        name: setup_repo
      with_dict: "{{ servers }}"

    - name: Iterate through role with items from hosts file
      include_role:
        name: install_dbserver
      with_dict: "{{ servers }}"

    - name: Iterate through role with items from hosts file
      include_role:
        name: init_dbserver
      with_dict: "{{ servers }}"

    - name: Iterate through role with items from hosts file
      include_role:
        name: setup_replication
      with_dict: "{{ servers }}"
