---
- hosts: localhost
  #vars:
  #  ansible_python_interpreter: /usr/bin/python2
  name: install, configure, initialize and replicate pg/epas on instances
  #connection: local
  become: true
  gather_facts: false

  collections:
    - edb_devops.edb_postgres

  vars_files:
    - hosts.yml

# internal processing purposes only
  pre_tasks:
    - name: initialize the user defined variables
      set_fact:
        os: "Centos7"
        pg_version: "12"
        pg_type: "EPAS"
        pg_data: "/data/pgdata"
        pg_wal: "/data/pg_wal"
        yum_username: ""
        yum_password: ""
        standby_quorum_type: "any"   # quorum type can be any or first
  roles:
    - setup_repo
    - install_dbserver
    - init_dbserver
    - setup_replication
    - setup_efm
