---
- hosts: localhost
  #vars:
  #  ansible_python_interpreter: /usr/bin/python2
  name: Install, Configure, Initialize and Replicate EPAS 12 and EFM 10 on Instances
  #connection: local
  become: true
  gather_facts: no

  collections:
    -  edb_devops.edb_postgres

  vars_files:
    - hosts.yml

# Internal processing purposes only
  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        OS: "RHEL7"
        PG_VERSION: "12"
        PG_TYPE: "EPAS"
        PG_DATA: "/data/pgdata"
        PG_WAL: "/data/pg_wal"
        EDB_YUM_USERNAME: ""
        EDB_YUM_PASSWORD: ""
        STANDBY_QUORUM_TYPE: "ANY" # Quorum type can be ANY or FIRST

tasks:
    - name: Iterate through role with items from hosts file
      include_role:
        name: process_vars
      with_dict: "{{ servers }}"

    - name: Iterate through role with items from hosts file
      include_role:
        name: setup_repo
      with_dict: "{{ servers }}"

    - name: Iterate through role with items from hosts file
      include_role:
        name: install_dbserver
      with_dict: "{{ servers }}"

    - name: Iterate through role with items from hosts file
      include_role:
        name: init_dbserver
      with_dict: "{{ servers }}"

    - name: Iterate through role with items from hosts file
      include_role:
        name: setup_replication
      with_dict: "{{ servers }}"

    - name: Iterate through role with items from hosts file
      include_role:
        name: setup_efm
      with_dict: "{{ servers }}"
