---
- hosts: localhost
  #vars:
  #  ansible_python_interpreter: /usr/bin/python2
  name: Setup PEM on Instances
  #connection: local
  become: true
  gather_facts: no

  collections:
    - edb_devops.edb_postgres

  vars_files:
    - hosts.yml

  # Initializing some variables
  vars:
    PEM_SERVER_PRIVATE_IP: ""
    PRIMARY_PRIVATE_IP: ""
    PRIMARY_PUBLIC_IP: ""
    STANDBY_NAMES: []
    ALL_NODE_IPS: []
    EFM_NODES_PRIVATE_IP: []
    EFM_NODES_PUBLIC_IP: []

  pre_tasks:
    # Define or re-define any variables previously assigned
    - name: Initialize the user defined variables
      set_fact:
        OS: "RHEL7"
        PG_TYPE: "EPAS"
        PG_VERSION: "12"
        EFM_VERSION: "EFM_VERSION"
        PG_DATA: "/data/pgdata"
        PG_EFM_USER: "efm"
        PG_EFM_USER_PASSWORD: "efm"
        ALL_NODE_IPS: "{{ ALL_NODE_IPS + [item.value.private_ip] }}"
        PEM_SERVER_PRIVATE_IP: "{{ PEM_SERVER_PRIVATE_IP + item.value.private_ip if(item.value.node_type == 'pemserver') else PEM_SERVER_PRIVATE_IP }}"
        PRIMARY_PRIVATE_IP: "{{ PRIMARY_PRIVATE_IP + item.value.private_ip if(item.value.node_type == 'primary') else PRIMARY_PRIVATE_IP }}"
        PRIMARY_PUBLIC_IP: "{{ PRIMARY_PUBLIC_IP  + item.value.public_ip if(item.value.node_type == 'primary') else PRIMARY_PUBLIC_IP }}"
      with_dict: "{{ servers }}"

    - name: Gather primary and standby nodes for EFM
      set_fact:
          EFM_NODES_PRIVATE_IP: "{{ EFM_NODES_PRIVATE_IP + [item.value.private_ip] }}"
          EFM_NODES_PUBLIC_IP: "{{ EFM_NODES_PUBLIC_IP + [item.value.public_ip] }}"
      when: item.value.node_type in ['primary', 'standby']
      with_dict: "{{ servers }}"

    - name: Gather the standby names
      set_fact:
        STANDBY_NAMES: "{{ STANDBY_NAMES + [item.key] }}"
      when: item.value.node_type == 'standby'
      with_dict: "{{ servers }}"

  tasks:
    - name: Iterate through repo role with items from hosts file
      include_role:
        name: setup_repo
      with_dict: "{{ servers }}"
    - name: Iterate through install role with items from hosts file
      include_role:
        name: install_dbserver
      with_dict: "{{ servers }}"
    - name: Iterate through role with items from hosts file
      include_role:
        name: init_dbserver
      with_dict: "{{ servers }}"
    - name: Iterate through role with items from hosts file
      include_role:
        name: setup_pem
      with_dict: "{{ servers }}"
