---

- name: Restart the EFM service
  systemd:
    name: "{{ EFM_SERVICE }}"
    enabled: yes
    state: restarted
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Reload the PG Service
  systemd:
    name: "{{ PG_SERVICE }}"
    state: reloaded
  become: yes
  delegate_to: "{{ item.value.public_ip }}"
